<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateReportsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('reports', function (Blueprint $table) {
            $table->engine = 'InnoDB';

            $table->increments('id');
            $table->unsignedInteger('teacher_id');
            $table->unsignedInteger('student_id');
            $table->timestamp('started_at')->nullable();
            $table->timestamp('ended_at')->nullable();
            $table->string('lesson_content')->nullable();
            $table->unsignedTinyInteger('lesson_stars')->default(0);
            $table->string('homework_content')->nullable();
            $table->unsignedTinyInteger('homework_stars')->default(0);
            $table->string('note')->nullable();
            $table->unsignedTinyInteger('is_public')->default(0)->comment('0-private 1-public');
            $table->unsignedTinyInteger('is_read')->default(0)->comment('0-private 1-public');
            $table->unsignedInteger('last_teacher_id')->nullable();
            $table->unsignedInteger('confirm_teacher_id')->nullable();
            $table->unsignedTinyInteger('updated_times')->default(0);
            $table->nullableTimestamps();

            $table->foreign('teacher_id')->references('id')->on('teachers')
                ->onUpdate('cascade')->onDelete('cascade');
            $table->foreign('student_id')->references('id')->on('students')
                ->onUpdate('cascade')->onDelete('cascade');
            $table->foreign('last_teacher_id')->references('id')->on('teachers')
                ->onUpdate('cascade')->onDelete('set null');
            $table->foreign('confirm_teacher_id')->references('id')->on('teachers')
                ->onUpdate('cascade')->onDelete('set null');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('reports');
    }
}
